### PR TITLE
Create 404 page

### PR DESCRIPTION
**Pull request by KazMalhotra**
The Github default 404 page is nice, but does not provide a link back to the setup.

### CODE REVIEW

**Comment by liamjwang** [comment]
Good catch, please [convert](https://html-to-pug.com/) the 404 page to .pug and request another review.
(I also added a license to the project so you might need to resolve the conflict)

**Review by liamjwang — CHANGES_REQUESTED** [review]
^

**Comment by KazMalhotra** [comment]
I updated and renamed the 404 file, and also updated package.json because in that file it says that the license is MIT, while the actual LICENSE file is GPL v3. I assumed the LICENSE file is correct, and updated package.json to the GPL v3. I also removed all conflicts.

**Review by liamjwang — APPROVED** [review]

**Comment by liamjwang** [comment]
Thanks!

**Pull request merged**
